language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install pyflakes pep8 coverage python-coveralls
  - python setup.py install
script:
  - pep8 storysniffer
  - pyflakes storysniffer
  - coverage run test.py
after_success:
  - coveralls
